# ipo_data.py
# Formatted data for Jasmine's HKEX 2026 IPO Dashboard

def load_verified_hk_ipos_part1():
    return [
        {
            "Ticker": "02513.HK",
            "CleanTicker": "02513",
            "English Name": "Z.AI",
            "Chinese Name": "智谱华章",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Artificial Intelligence & LLM",
            "Listing Date": "2026-01-08",
            "Offering Price": "HKD 890.50"
        },
        {
            "Ticker": "03986.HK",
            "CleanTicker": "03986",
            "English Name": "GIGADEVICE",
            "Chinese Name": "兆易创新",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Semiconductors",
            "Listing Date": "2026-01-10",
            "Offering Price": "HKD 533.50"
        },
        {
            "Ticker": "09903.HK",
            "CleanTicker": "09903",
            "English Name": "ILUVATAR COREX",
            "Chinese Name": "天数智芯",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Artificial Intelligence & Chips",
            "Listing Date": "2026-01-12",
            "Offering Price": "HKD 519.50"
        },
        {
            "Ticker": "06809.HK",
            "CleanTicker": "06809",
            "English Name": "MONTAGE TECH",
            "Chinese Name": "澜起科技",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Semiconductors",
            "Listing Date": "2026-01-15",
            "Offering Price": "HKD 264.00"
        },
        {
            "Ticker": "00100.HK",
            "CleanTicker": "00100",
            "English Name": "MINIMAX-W",
            "Chinese Name": "稀宇科技",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Artificial Intelligence & LLM",
            "Listing Date": "2026-01-09",
            "Offering Price": "HKD 193.10"
        },
        {
            "Ticker": "06082.HK",
            "CleanTicker": "06082",
            "English Name": "BIREN TECH",
            "Chinese Name": "壁仞科技",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Artificial Intelligence & Chips",
            "Listing Date": "2026-01-18",
            "Offering Price": "HKD 34.46"
        },
        {
            "Ticker": "02476.HK",
            "CleanTicker": "02476",
            "English Name": "VGT",
            "Chinese Name": "胜脉电子",
            "Exchange": "Main Board",
            "Industry": "Industrial Goods",
            "Sub-Sector": "Electronic Components",
            "Listing Date": "2026-01-20",
            "Offering Price": "HKD 212.40"
        },
        {
            "Ticker": "02475.HK",
            "CleanTicker": "02475",
            "English Name": "LUXSHARE ICT",
            "Chinese Name": "立讯精密",
            "Exchange": "Main Board",
            "Industry": "Industrial Goods",
            "Sub-Sector": "Electronic Components",
            "Listing Date": "2026-07-09",
            "Offering Price": "HKD 52.20"
        },
        {
            "Ticker": "02715.HK",
            "CleanTicker": "02715",
            "English Name": "ESTUN",
            "Chinese Name": "埃斯顿",
            "Exchange": "Main Board",
            "Industry": "Industrial Goods",
            "Sub-Sector": "Robotics & Automation",
            "Listing Date": "2026-01-22",
            "Offering Price": "HKD 18.39"
        },
        {
            "Ticker": "02249.HK",
            "CleanTicker": "02249",
            "English Name": "NEXCHIP",
            "Chinese Name": "晶合集成",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Semiconductors",
            "Listing Date": "2026-07-10",
            "Offering Price": "HKD 29.60"
        },
        {
            "Ticker": "01688.HK",
            "CleanTicker": "01688",
            "English Name": "LINGYI ITECH",
            "Chinese Name": "领益智造",
            "Exchange": "Main Board",
            "Industry": "Industrial Goods",
            "Sub-Sector": "Precision Manufacturing",
            "Listing Date": "2026-01-25",
            "Offering Price": "HKD 6.49"
        },
        {
            "Ticker": "06951.HK",
            "CleanTicker": "06951",
            "English Name": "CCTC",
            "Chinese Name": "中瓷电子",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Electronic Materials",
            "Listing Date": "2026-01-28",
            "Offering Price": "HKD 90.50"
        },
        {
            "Ticker": "01989.HK",
            "CleanTicker": "01989",
            "English Name": "DELTON",
            "Chinese Name": "德尔股份",
            "Exchange": "Main Board",
            "Industry": "Automotive",
            "Sub-Sector": "Auto Components",
            "Listing Date": "2026-02-02",
            "Offering Price": "HKD 117.70"
        },
        {
            "Ticker": "03296.HK",
            "CleanTicker": "03296",
            "English Name": "HUAQIN",
            "Chinese Name": "华勤技术",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Smart Hardware",
            "Listing Date": "2026-02-05",
            "Offering Price": "HKD 61.45"
        },
        {
            "Ticker": "03200.HK",
            "CleanTicker": "03200",
            "English Name": "HANS CNC",
            "Chinese Name": "大族数控",
            "Exchange": "Main Board",
            "Industry": "Industrial Goods",
            "Sub-Sector": "Industrial Machinery",
            "Listing Date": "2026-02-08",
            "Offering Price": "HKD 110.00"
        },
        {
            "Ticker": "01377.HK",
            "CleanTicker": "01377",
            "English Name": "DTECH",
            "Chinese Name": "帝科股份",
            "Exchange": "Main Board",
            "Industry": "Materials",
            "Sub-Sector": "Electronic Materials",
            "Listing Date": "2026-02-10",
            "Offering Price": "HKD 330.80"
        },
        {
            "Ticker": "02768.HK",
            "CleanTicker": "02768",
            "English Name": "GON TECHNOLOGY",
            "Chinese Name": "国轩高科",
            "Exchange": "Main Board",
            "Industry": "Energy",
            "Sub-Sector": "Battery Technology",
            "Listing Date": "2026-02-12",
            "Offering Price": "HKD 27.38"
        },
        {
            "Ticker": "02714.HK",
            "CleanTicker": "02714",
            "English Name": "MUYUAN",
            "Chinese Name": "牧原股份",
            "Exchange": "Main Board",
            "Industry": "Consumer Staples",
            "Sub-Sector": "Agriculture & Food",
            "Listing Date": "2026-02-15",
            "Offering Price": "HKD 33.88"
        },
        {
            "Ticker": "00668.HK",
            "CleanTicker": "00668",
            "English Name": "ANKER",
            "Chinese Name": "安克创新",
            "Exchange": "Main Board",
            "Industry": "Consumer Discretionary",
            "Sub-Sector": "Smart Hardware",
            "Listing Date": "2026-07-02",
            "Offering Price": "HKD 103.60"
        },
        {
            "Ticker": "02701.HK",
            "CleanTicker": "02701",
            "English Name": "NSING TECH",
            "Chinese Name": "联动科技",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Semiconductor Equipment",
            "Listing Date": "2026-02-18",
            "Offering Price": "HKD 9.10"
        },
        {
            "Ticker": "00501.HK",
            "CleanTicker": "00501",
            "English Name": "OMNIVISION",
            "Chinese Name": "韦尔股份",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Semiconductors",
            "Listing Date": "2026-02-20",
            "Offering Price": "HKD 83.55"
        },
        {
            "Ticker": "06745.HK",
            "CleanTicker": "06745",
            "English Name": "BEFAR GROUP",
            "Chinese Name": "滨化集团",
            "Exchange": "Main Board",
            "Industry": "Materials",
            "Sub-Sector": "Chemicals",
            "Listing Date": "2026-07-10",
            "Offering Price": "HKD 3.10"
        },
        {
            "Ticker": "01768.HK",
            "CleanTicker": "01768",
            "English Name": "BUSYMING",
            "Chinese Name": "斑马消费",
            "Exchange": "Main Board",
            "Industry": "Consumer Discretionary",
            "Sub-Sector": "Retail & Services",
            "Listing Date": "2026-02-22",
            "Offering Price": "HKD 390.80"
        },
        {
            "Ticker": "01879.HK",
            "CleanTicker": "01879",
            "English Name": "XIZHI TECH-P",
            "Chinese Name": "希荻微",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Analog Semiconductors",
            "Listing Date": "2026-02-25",
            "Offering Price": "HKD 279.20"
        },
        {
            "Ticker": "03277.HK",
            "CleanTicker": "03277",
            "English Name": "GPIXEL",
            "Chinese Name": "长光辰芯",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Optoelectronics",
            "Listing Date": "2026-02-28",
            "Offering Price": "HKD 62.70"
        },
        {
            "Ticker": "09630.HK",
            "CleanTicker": "09630",
            "English Name": "CFMEE",
            "Chinese Name": "中车机械",
            "Exchange": "Main Board",
            "Industry": "Industrial Goods",
            "Sub-Sector": "Heavy Equipment",
            "Listing Date": "2026-03-02",
            "Offering Price": "HKD 304.40"
        },
        {
            "Ticker": "00470.HK",
            "CleanTicker": "00470",
            "English Name": "WUXI LEAD",
            "Chinese Name": "先导智能",
            "Exchange": "Main Board",
            "Industry": "Industrial Goods",
            "Sub-Sector": "New Energy Equipment",
            "Listing Date": "2026-03-05",
            "Offering Price": "HKD 27.70"
        },
        {
            "Ticker": "02723.HK",
            "CleanTicker": "02723",
            "English Name": "DEEPZERO",
            "Chinese Name": "深度零度",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Artificial Intelligence",
            "Listing Date": "2026-03-08",
            "Offering Price": "HKD 520.00"
        },
        {
            "Ticker": "06810.HK",
            "CleanTicker": "06810",
            "English Name": "SUNMI TECH-W",
            "Chinese Name": "商米科技",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "IoT Hardware",
            "Listing Date": "2026-03-10",
            "Offering Price": "HKD 56.50"
        },
        {
            "Ticker": "03661.HK",
            "CleanTicker": "03661",
            "English Name": "SG MICRO",
            "Chinese Name": "圣邦股份",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Analog Chips",
            "Listing Date": "2026-03-12",
            "Offering Price": "HKD 95.75"
        },
        {
            "Ticker": "01191.HK",
            "CleanTicker": "01191",
            "English Name": "CREALIGHTS",
            "Chinese Name": "光峰科技",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Laser Display",
            "Listing Date": "2026-03-15",
            "Offering Price": "HKD 90.25"
        },
        {
            "Ticker": "02697.HK",
            "CleanTicker": "02697",
            "English Name": "TH MEDICAL-B",
            "Chinese Name": "泰合医疗",
            "Exchange": "Main Board",
            "Industry": "Healthcare",
            "Sub-Sector": "Biotech",
            "Listing Date": "2026-03-18",
            "Offering Price": "HKD 451.20"
        },
        {
            "Ticker": "02335.HK",
            "CleanTicker": "02335",
            "English Name": "MICOT PHARMA-B",
            "Chinese Name": "麦科医药",
            "Exchange": "Main Board",
            "Industry": "Healthcare",
            "Sub-Sector": "Pharmaceuticals",
            "Listing Date": "2026-03-20",
            "Offering Price": "HKD 35.50"
        },
        {
            "Ticker": "06871.HK",
            "CleanTicker": "06871",
            "English Name": "ROBOTPHOENIX",
            "Chinese Name": "翼菲机器人",
            "Exchange": "Main Board",
            "Industry": "Industrial Goods",
            "Sub-Sector": "Robotics",
            "Listing Date": "2026-03-22",
            "Offering Price": "HKD 29.00"
        },
        {
            "Ticker": "03268.HK",
            "CleanTicker": "03268",
            "English Name": "MEIG",
            "Chinese Name": "美格智能",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Wireless Modules",
            "Listing Date": "2026-03-25",
            "Offering Price": "HKD 17.22"
        },
        {
            "Ticker": "02797.HK",
            "CleanTicker": "02797",
            "English Name": "QIYUNSHAN FOOD",
            "Chinese Name": "齐云山食品",
            "Exchange": "Main Board",
            "Industry": "Consumer Staples",
            "Sub-Sector": "Food & Beverage",
            "Listing Date": "2026-03-28",
            "Offering Price": "HKD 32.98"
        },
        {
            "Ticker": "06915.HK",
            "CleanTicker": "06915",
            "English Name": "JIANGXI BIO",
            "Chinese Name": "江西生物",
            "Exchange": "Main Board",
            "Industry": "Healthcare",
            "Sub-Sector": "Biotech",
            "Listing Date": "2026-03-30",
            "Offering Price": "HKD 8.95"
        },
        {
            "Ticker": "06656.HK",
            "CleanTicker": "06656",
            "English Name": "SIGENERGY",
            "Chinese Name": "采日能源",
            "Exchange": "Main Board",
            "Industry": "Energy",
            "Sub-Sector": "Energy Storage",
            "Listing Date": "2026-04-02",
            "Offering Price": "HKD 276.60"
        },
        {
            "Ticker": "03952.HK",
            "CleanTicker": "03952",
            "English Name": "LAIFUAL",
            "Chinese Name": "来福谐波",
            "Exchange": "Main Board",
            "Industry": "Industrial Goods",
            "Sub-Sector": "Robotics & Drives",
            "Listing Date": "2026-06-30",
            "Offering Price": "HKD 64.20"
        },
        {
            "Ticker": "01511.HK",
            "CleanTicker": "01511",
            "English Name": "UISEE TECH",
            "Chinese Name": "纵目科技",
            "Exchange": "Main Board",
            "Industry": "Automotive",
            "Sub-Sector": "Autonomous Driving",
            "Listing Date": "2026-04-05",
            "Offering Price": "HKD 58.00"
        },
        {
            "Ticker": "09980.HK",
            "CleanTicker": "09980",
            "English Name": "EASTROC",
            "Chinese Name": "东鹏饮料",
            "Exchange": "Main Board",
            "Industry": "Consumer Staples",
            "Sub-Sector": "Beverages",
            "Listing Date": "2026-04-08",
            "Offering Price": "HKD 112.60"
        },
        {
            "Ticker": "02726.HK",
            "CleanTicker": "02726",
            "English Name": "EPIWORLD",
            "Chinese Name": "瀚天天成",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Semiconductors",
            "Listing Date": "2026-04-10",
            "Offering Price": "HKD 101.90"
        },
        {
            "Ticker": "06715.HK",
            "CleanTicker": "06715",
            "English Name": "XUNLONG SCITECH",
            "Chinese Name": "迅龙科创",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Hardware",
            "Listing Date": "2026-04-12",
            "Offering Price": "HKD 70.50"
        },
        {
            "Ticker": "07687.HK",
            "CleanTicker": "07687",
            "English Name": "EACON",
            "Chinese Name": "易控智驾",
            "Exchange": "Main Board",
            "Industry": "Automotive",
            "Sub-Sector": "Autonomous Driving",
            "Listing Date": "2026-04-15",
            "Offering Price": "HKD 86.15"
        },
        {
            "Ticker": "01187.HK",
            "CleanTicker": "01187",
            "English Name": "COFOE MEDICAL",
            "Chinese Name": "可孚医疗",
            "Exchange": "Main Board",
            "Industry": "Healthcare",
            "Sub-Sector": "Medical Devices",
            "Listing Date": "2026-04-18",
            "Offering Price": "HKD 34.40"
        },
        {
            "Ticker": "02692.HK",
            "CleanTicker": "02692",
            "English Name": "ZHAOWEI",
            "Chinese Name": "兆威机电",
            "Exchange": "Main Board",
            "Industry": "Industrial Goods",
            "Sub-Sector": "Micro Drives",
            "Listing Date": "2026-04-20",
            "Offering Price": "HKD 45.40"
        },
        {
            "Ticker": "00600.HK",
            "CleanTicker": "00600",
            "English Name": "AXERA",
            "Chinese Name": "爱芯元智",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "AI Chips",
            "Listing Date": "2026-04-22",
            "Offering Price": "HKD 11.82"
        },
        {
            "Ticker": "02706.HK",
            "CleanTicker": "02706",
            "English Name": "HAIZHI TECH GP",
            "Chinese Name": "海智科技",
            "Exchange": "Main Board",
            "Industry": "Industrial Goods",
            "Sub-Sector": "Industrial Services",
            "Listing Date": "2026-04-25",
            "Offering Price": "HKD 33.18"
        },
        {
            "Ticker": "01081.HK",
            "CleanTicker": "01081",
            "English Name": "DAJIN",
            "Chinese Name": "大金重工",
            "Exchange": "Main Board",
            "Industry": "Energy",
            "Sub-Sector": "Wind Power Equipment",
            "Listing Date": "2026-04-28",
            "Offering Price": "HKD 32.78"
        },
        {
            "Ticker": "06067.HK",
            "CleanTicker": "06067",
            "English Name": "SENIOR MATERIAL",
            "Chinese Name": "星源材质",
            "Exchange": "Main Board",
            "Industry": "Materials",
            "Sub-Sector": "Battery Separators",
            "Listing Date": "2026-04-30",
            "Offering Price": "HKD 7.50"
        },
        {
            "Ticker": "09971.HK",
            "CleanTicker": "09971",
            "English Name": "BASICSEMI",
            "Chinese Name": "基本半导体",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Power Semiconductors",
            "Listing Date": "2026-07-08",
            "Offering Price": "HKD 40.30"
        }
    ]

def load_verified_hk_ipos_part2():
    return [
        {
            "Ticker": "06228.HK",
            "CleanTicker": "06228",
            "English Name": "MERDEKAGOLD-DRS",
            "Chinese Name": "独立黄金",
            "Exchange": "Main Board",
            "Industry": "Materials",
            "Sub-Sector": "Mining",
            "Listing Date": "2026-05-02",
            "Offering Price": "HKD 24.20"
        },
        {
            "Ticker": "06880.HK",
            "CleanTicker": "06880",
            "English Name": "MOMENTA-W",
            "Chinese Name": "初速度",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Autonomous Driving",
            "Listing Date": "2026-07-08",
            "Offering Price": "HKD 261.40"
        },
        {
            "Ticker": "07688.HK",
            "CleanTicker": "07688",
            "English Name": "TOPN",
            "Chinese Name": "拓璞科技",
            "Exchange": "Main Board",
            "Industry": "Industrial Goods",
            "Sub-Sector": "Equipment",
            "Listing Date": "2026-05-05",
            "Offering Price": "HKD 13.71"
        },
        {
            "Ticker": "01779.HK",
            "CleanTicker": "01779",
            "English Name": "LONGBIO-B",
            "Chinese Name": "隆生物联",
            "Exchange": "Main Board",
            "Industry": "Healthcare",
            "Sub-Sector": "Biotech",
            "Listing Date": "2026-05-08",
            "Offering Price": "HKD 91.15"
        },
        {
            "Ticker": "00537.HK",
            "CleanTicker": "00537",
            "English Name": "RIGOL",
            "Chinese Name": "普源精电",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Electronic Test Instruments",
            "Listing Date": "2026-05-10",
            "Offering Price": "HKD 23.92"
        },
        {
            "Ticker": "00901.HK",
            "CleanTicker": "00901",
            "English Name": "SDM",
            "Chinese Name": "圣德慕",
            "Exchange": "Main Board",
            "Industry": "Consumer Discretionary",
            "Sub-Sector": "Services",
            "Listing Date": "2026-05-12",
            "Offering Price": "HKD 57.25"
        },
        {
            "Ticker": "00068.HK",
            "CleanTicker": "00068",
            "English Name": "MANYCORE TECH",
            "Chinese Name": "群核科技",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Cloud Software",
            "Listing Date": "2026-05-15",
            "Offering Price": "HKD 8.06"
        },
        {
            "Ticker": "06938.HK",
            "CleanTicker": "06938",
            "English Name": "RIBOLIFE-B",
            "Chinese Name": "锐博生物",
            "Exchange": "Main Board",
            "Industry": "Healthcare",
            "Sub-Sector": "Biotech",
            "Listing Date": "2026-05-18",
            "Offering Price": "HKD 51.20"
        },
        {
            "Ticker": "01956.HK",
            "CleanTicker": "01956",
            "English Name": "WENGE AI",
            "Chinese Name": "文因东方",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Artificial Intelligence",
            "Listing Date": "2026-05-20",
            "Offering Price": "HKD 63.00"
        },
        {
            "Ticker": "07656.HK",
            "CleanTicker": "07656",
            "English Name": "RECONOVA",
            "Chinese Name": "锐角科技",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Smart Hardware",
            "Listing Date": "2026-05-22",
            "Offering Price": "HKD 24.80"
        },
        {
            "Ticker": "06872.HK",
            "CleanTicker": "06872",
            "English Name": "TENNOR THERAP-B",
            "Chinese Name": "天诺医药",
            "Exchange": "Main Board",
            "Industry": "Healthcare",
            "Sub-Sector": "Biotech",
            "Listing Date": "2026-05-25",
            "Offering Price": "HKD 172.70"
        },
        {
            "Ticker": "07489.HK",
            "CleanTicker": "07489",
            "English Name": "VOYAH AUTO",
            "Chinese Name": "岚图汽车",
            "Exchange": "Main Board",
            "Industry": "Automotive",
            "Sub-Sector": "New Energy Vehicles",
            "Listing Date": "2026-05-28",
            "Offering Price": "HKD 2.98"
        },
        {
            "Ticker": "02526.HK",
            "CleanTicker": "02526",
            "English Name": "DIAGENS-B",
            "Chinese Name": "达吉恩生物",
            "Exchange": "Main Board",
            "Industry": "Healthcare",
            "Sub-Sector": "Biotech",
            "Listing Date": "2026-05-30",
            "Offering Price": "HKD 270.60"
        },
        {
            "Ticker": "02290.HK",
            "CleanTicker": "02290",
            "English Name": "LUNG FUNG GROUP",
            "Chinese Name": "龙丰集团",
            "Exchange": "Main Board",
            "Industry": "Consumer Discretionary",
            "Sub-Sector": "Retail",
            "Listing Date": "2026-06-02",
            "Offering Price": "HKD 3.74"
        },
        {
            "Ticker": "02672.HK",
            "CleanTicker": "02672",
            "English Name": "BAIGE DIGITAL",
            "Chinese Name": "百歌数字",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Digital Media",
            "Listing Date": "2026-06-05",
            "Offering Price": "HKD 61.50"
        },
        {
            "Ticker": "02729.HK",
            "CleanTicker": "02729",
            "English Name": "GALAXIS TECH",
            "Chinese Name": "哥利斯科技",
            "Exchange": "Main Board",
            "Industry": "Industrial Goods",
            "Sub-Sector": "Automation",
            "Listing Date": "2026-06-08",
            "Offering Price": "HKD 27.16"
        },
        {
            "Ticker": "09611.HK",
            "CleanTicker": "09611",
            "English Name": "LONGCHEER",
            "Chinese Name": "龙旗科技",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "OEM / ODM Electronics",
            "Listing Date": "2026-06-10",
            "Offering Price": "HKD 21.20"
        },
        {
            "Ticker": "03625.HK",
            "CleanTicker": "03625",
            "English Name": "FOURSEMI",
            "Chinese Name": "富特科技",
            "Exchange": "Main Board",
            "Industry": "Automotive",
            "Sub-Sector": "EV Power Systems",
            "Listing Date": "2026-06-12",
            "Offering Price": "HKD 77.10"
        },
        {
            "Ticker": "03752.HK",
            "CleanTicker": "03752",
            "English Name": "ROKAE ROBOTICS",
            "Chinese Name": "珞石机器人",
            "Exchange": "Main Board",
            "Industry": "Industrial Goods",
            "Sub-Sector": "Robotics",
            "Listing Date": "2026-06-15",
            "Offering Price": "HKD 48.02"
        },
        {
            "Ticker": "06106.HK",
            "CleanTicker": "06106",
            "English Name": "SEER TECH",
            "Chinese Name": "仙工智能",
            "Exchange": "Main Board",
            "Industry": "Industrial Goods",
            "Sub-Sector": "Mobile Robots",
            "Listing Date": "2026-06-18",
            "Offering Price": "HKD 60.00"
        },
        {
            "Ticker": "09981.HK",
            "CleanTicker": "09981",
            "English Name": "WOER",
            "Chinese Name": "沃尔核材",
            "Exchange": "Main Board",
            "Industry": "Industrial Goods",
            "Sub-Sector": "New Materials",
            "Listing Date": "2026-06-20",
            "Offering Price": "HKD 10.38"
        },
        {
            "Ticker": "07666.HK",
            "CleanTicker": "07666",
            "English Name": "METIS TECHBIO-P",
            "Chinese Name": "美迪西生物",
            "Exchange": "Main Board",
            "Industry": "Healthcare",
            "Sub-Sector": "Biotech",
            "Listing Date": "2026-06-22",
            "Offering Price": "HKD 10.64"
        },
        {
            "Ticker": "02675.HK",
            "CleanTicker": "02675",
            "English Name": "EDGE MEDICAL-B",
            "Chinese Name": "精锋医疗",
            "Exchange": "Main Board",
            "Industry": "Healthcare",
            "Sub-Sector": "Medical Devices",
            "Listing Date": "2026-06-25",
            "Offering Price": "HKD 37.30"
        },
        {
            "Ticker": "06658.HK",
            "CleanTicker": "06658",
            "English Name": "LIULIUMEI",
            "Chinese Name": "溜溜梅",
            "Exchange": "Main Board",
            "Industry": "Consumer Staples",
            "Sub-Sector": "Food & Beverage",
            "Listing Date": "2026-06-28",
            "Offering Price": "HKD 156.90"
        },
        {
            "Ticker": "02493.HK",
            "CleanTicker": "02493",
            "English Name": "MABWELL-B",
            "Chinese Name": "迈威生物",
            "Exchange": "Main Board",
            "Industry": "Healthcare",
            "Sub-Sector": "Biotech",
            "Listing Date": "2026-07-01",
            "Offering Price": "HKD 23.46"
        },
        {
            "Ticker": "01021.HK",
            "CleanTicker": "01021",
            "English Name": "HUAYAN ROBOTICS",
            "Chinese Name": "华研机器人",
            "Exchange": "Main Board",
            "Industry": "Industrial Goods",
            "Sub-Sector": "Robotics",
            "Listing Date": "2026-07-03",
            "Offering Price": "HKD 11.30"
        },
        {
            "Ticker": "06636.HK",
            "CleanTicker": "06636",
            "English Name": "EXTREME VISION",
            "Chinese Name": "极视角",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Computer Vision AI",
            "Listing Date": "2026-07-05",
            "Offering Price": "HKD 74.00"
        },
        {
            "Ticker": "01609.HK",
            "CleanTicker": "01609",
            "English Name": "STAR SPORTS MED",
            "Chinese Name": "星运动医学",
            "Exchange": "Main Board",
            "Industry": "Healthcare",
            "Sub-Sector": "Medical Devices",
            "Listing Date": "2026-07-07",
            "Offering Price": "HKD 137.40"
        },
        {
            "Ticker": "03310.HK",
            "CleanTicker": "03310",
            "English Name": "VIEWTRIX TECH",
            "Chinese Name": "维信诺科技",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Displays",
            "Listing Date": "2026-07-09",
            "Offering Price": "HKD 29.30"
        },
        {
            "Ticker": "02272.HK",
            "CleanTicker": "02272",
            "English Name": "KEYTOP PARKING",
            "Chinese Name": "科拓停车",
            "Exchange": "Main Board",
            "Industry": "Industrial Goods",
            "Sub-Sector": "Smart Parking",
            "Listing Date": "2026-07-11",
            "Offering Price": "HKD 110.90"
        },
        {
            "Ticker": "03388.HK",
            "CleanTicker": "03388",
            "English Name": "CREALITY",
            "Chinese Name": "创想三维",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "3D Printers",
            "Listing Date": "2026-07-13",
            "Offering Price": "HKD 18.80"
        },
        {
            "Ticker": "06675.HK",
            "CleanTicker": "06675",
            "English Name": "SENASI",
            "Chinese Name": "森思捷",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Software",
            "Listing Date": "2026-07-14",
            "Offering Price": "HKD 20.20"
        },
        {
            "Ticker": "03355.HK",
            "CleanTicker": "03355",
            "English Name": "FS.COM",
            "Chinese Name": "飞速创新",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Network Equipment",
            "Listing Date": "2026-07-15",
            "Offering Price": "HKD 34.52"
        },
        {
            "Ticker": "06132.HK",
            "CleanTicker": "06132",
            "English Name": "HJ SCIENCE-B",
            "Chinese Name": "汇聚科技",
            "Exchange": "Main Board",
            "Industry": "Healthcare",
            "Sub-Sector": "Biotech",
            "Listing Date": "2026-07-16",
            "Offering Price": "HKD 39.94"
        },
        {
            "Ticker": "07630.HK",
            "CleanTicker": "07630",
            "English Name": "IMPACT THERAP-B",
            "Chinese Name": "创响生物",
            "Exchange": "Main Board",
            "Industry": "Healthcare",
            "Sub-Sector": "Biotech",
            "Listing Date": "2026-07-17",
            "Offering Price": "HKD 13.23"
        },
        {
            "Ticker": "01392.HK",
            "CleanTicker": "01392",
            "English Name": "HQVT",
            "Chinese Name": "华强方特",
            "Exchange": "Main Board",
            "Industry": "Consumer Discretionary",
            "Sub-Sector": "Entertainment",
            "Listing Date": "2026-07-18",
            "Offering Price": "HKD 13.70"
        },
        {
            "Ticker": "02553.HK",
            "CleanTicker": "02553",
            "English Name": "SHOUGANG LANZA",
            "Chinese Name": "首钢朗泽",
            "Exchange": "Main Board",
            "Industry": "Materials",
            "Sub-Sector": "Green Tech",
            "Listing Date": "2026-07-19",
            "Offering Price": "HKD 23.04"
        },
        {
            "Ticker": "02667.HK",
            "CleanTicker": "02667",
            "English Name": "TONGRENTANGCARE",
            "Chinese Name": "同仁堂健康",
            "Exchange": "Main Board",
            "Industry": "Healthcare",
            "Sub-Sector": "Traditional Medicine",
            "Listing Date": "2026-07-20",
            "Offering Price": "HKD 2.93"
        },
        {
            "Ticker": "09637.HK",
            "CleanTicker": "09637",
            "English Name": "ALEBUND-B",
            "Chinese Name": "岸迈生物",
            "Exchange": "Main Board",
            "Industry": "Healthcare",
            "Sub-Sector": "Biotech",
            "Listing Date": "2026-07-20",
            "Offering Price": "HKD 28.14"
        },
        {
            "Ticker": "01770.HK",
            "CleanTicker": "01770",
            "English Name": "DKE",
            "Chinese Name": "大科电子",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Electronics",
            "Listing Date": "2026-07-20",
            "Offering Price": "HKD 77.80"
        },
        {
            "Ticker": "01236.HK",
            "CleanTicker": "01236",
            "English Name": "LDROBOT",
            "Chinese Name": "雷动机器人",
            "Exchange": "Main Board",
            "Industry": "Industrial Goods",
            "Sub-Sector": "Robotics",
            "Listing Date": "2026-07-20",
            "Offering Price": "HKD 33.16"
        },
        {
            "Ticker": "03636.HK",
            "CleanTicker": "03636",
            "English Name": "JINXUN RESOURCE",
            "Chinese Name": "金讯资源",
            "Exchange": "Main Board",
            "Industry": "Materials",
            "Sub-Sector": "Resources",
            "Listing Date": "2026-07-20",
            "Offering Price": "HKD 12.50"
        },
        {
            "Ticker": "02632.HK",
            "CleanTicker": "02632",
            "English Name": "NEW VISION CO",
            "Chinese Name": "新视界",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Software",
            "Listing Date": "2026-07-20",
            "Offering Price": "HKD 63.50"
        },
        {
            "Ticker": "02720.HK",
            "CleanTicker": "02720",
            "English Name": "RIDGE OUTDOOR",
            "Chinese Name": "瑞杰户外",
            "Exchange": "Main Board",
            "Industry": "Consumer Discretionary",
            "Sub-Sector": "Outdoor Equipment",
            "Listing Date": "2026-07-20",
            "Offering Price": "HKD 21.48"
        },
        {
            "Ticker": "02677.HK",
            "CleanTicker": "02677",
            "English Name": "DISTINCT HEALTH",
            "Chinese Name": "明桥健康",
            "Exchange": "Main Board",
            "Industry": "Healthcare",
            "Sub-Sector": "Healthcare Services",
            "Listing Date": "2026-07-20",
            "Offering Price": "HKD 25.50"
        },
        {
            "Ticker": "00664.HK",
            "CleanTicker": "00664",
            "English Name": "TONGSHIFU",
            "Chinese Name": "铜师傅",
            "Exchange": "Main Board",
            "Industry": "Consumer Discretionary",
            "Sub-Sector": "Home Goods",
            "Listing Date": "2026-07-20",
            "Offering Price": "HKD 13.78"
        },
        {
            "Ticker": "08090.HK",
            "CleanTicker": "08090",
            "English Name": "BAOGAI",
            "Chinese Name": "宝盖科技",
            "Exchange": "GEM",
            "Industry": "Industrial Goods",
            "Sub-Sector": "Manufacturing",
            "Listing Date": "2026-07-20",
            "Offering Price": "HKD 5.30"
        },
        {
            "Ticker": "01641.HK",
            "CleanTicker": "01641",
            "English Name": "HX COLDCHAIN",
            "Chinese Name": "华夏冷链",
            "Exchange": "Main Board",
            "Industry": "Industrials",
            "Sub-Sector": "Logistics",
            "Listing Date": "2026-07-20",
            "Offering Price": "HKD 4.44"
        },
        {
            "Ticker": "08610.HK",
            "CleanTicker": "08610",
            "English Name": "BBSB INTL",
            "Chinese Name": "宝光国际",
            "Exchange": "GEM",
            "Industry": "Consumer Discretionary",
            "Sub-Sector": "Retail",
            "Listing Date": "2026-07-20",
            "Offering Price": "HKD 0.59"
        }
    ]
