def load_verified_hk_ipos_part2():
    return [
        {
            "Ticker": "02511.HK",
            "CleanTicker": "02511",
            "English Name": "SHANGHAI BAOSIGHT SOFTWARE CO., LTD.",
            "Chinese Name": "宝信软件",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Industrial Software & IT",
            "Listing Date": "2026-05-20",
            "Offering Price": "HKD 41.50"
        },
        {
            "Ticker": "06311.HK",
            "CleanTicker": "06311",
            "English Name": "JOINCARE PHARMACEUTICAL GROUP INDUSTRY CO., LTD.",
            "Chinese Name": "丽珠集团",
            "Exchange": "Main Board",
            "Industry": "Healthcare",
            "Sub-Sector": "Pharmaceuticals",
            "Listing Date": "2026-05-15",
            "Offering Price": "HKD 28.90"
        },
        {
            "Ticker": "02988.HK",
            "CleanTicker": "02988",
            "English Name": "NINGBO BOWAY ALLOY MATERIAL CO., LTD.",
            "Chinese Name": "博威合金",
            "Exchange": "Main Board",
            "Industry": "Materials",
            "Sub-Sector": "Non-ferrous Metals",
            "Listing Date": "2026-05-14",
            "Offering Price": "HKD 17.60"
        },
        {
            "Ticker": "01655.HK",
            "CleanTicker": "01655",
            "English Name": "QINGDAO HAIER BIOMEDICAL CO., LTD.",
            "Chinese Name": "海尔生物",
            "Exchange": "Main Board",
            "Industry": "Healthcare",
            "Sub-Sector": "Biosecurity & Cold Chain",
            "Listing Date": "2026-05-13",
            "Offering Price": "HKD 24.30"
        },
        {
            "Ticker": "07422.HK",
            "CleanTicker": "07422",
            "English Name": "ZHEJIANG CENTURY HUATONG GROUP CO., LTD.",
            "Chinese Name": "世纪华通",
            "Exchange": "Main Board",
            "Industry": "Communication Services",
            "Sub-Sector": "Digital Entertainment",
            "Listing Date": "2026-05-08",
            "Offering Price": "HKD 8.90"
        },
        {
            "Ticker": "02199.HK",
            "CleanTicker": "02199",
            "English Name": "GUANGZHOU SHIYUAN ELECTRONIC TECHNOLOGY CO., LTD.",
            "Chinese Name": "视源股份",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Interactive Display Systems",
            "Listing Date": "2026-05-07",
            "Offering Price": "HKD 51.40"
        },
        {
            "Ticker": "06822.HK",
            "CleanTicker": "06822",
            "English Name": "SHENZHEN INOVANCE TECHNOLOGY CO., LTD.",
            "Chinese Name": "汇川技术",
            "Exchange": "Main Board",
            "Industry": "Industrials",
            "Sub-Sector": "Industrial Automation",
            "Listing Date": "2026-05-06",
            "Offering Price": "HKD 68.50"
        },
        {
            "Ticker": "03122.HK",
            "CleanTicker": "03122",
            "English Name": "JIANGSU HENGRUI PHARMACEUTICALS CO., LTD.",
            "Chinese Name": "恒瑞医药",
            "Exchange": "Main Board",
            "Industry": "Healthcare",
            "Sub-Sector": "Innovative Drugs",
            "Listing Date": "2026-04-30",
            "Offering Price": "HKD 48.00"
        },
        {
            "Ticker": "01833.HK",
            "CleanTicker": "01833",
            "English Name": "BEIJING ORIENTAL YUHONG WATERPROOF TECHNOLOGY CO., LTD.",
            "Chinese Name": "东方雨虹",
            "Exchange": "Main Board",
            "Industry": "Materials",
            "Sub-Sector": "Building Materials",
            "Listing Date": "2026-04-29",
            "Offering Price": "HKD 15.20"
        },
        {
            "Ticker": "02722.HK",
            "CleanTicker": "02722",
            "English Name": "SHANDONG WEIGAO GROUP MEDICAL POLYMER COMPANY LIMITED",
            "Chinese Name": "威高骨科",
            "Exchange": "Main Board",
            "Industry": "Healthcare",
            "Sub-Sector": "Orthopedic Devices",
            "Listing Date": "2026-04-28",
            "Offering Price": "HKD 22.10"
        },
        {
            "Ticker": "06211.HK",
            "CleanTicker": "06211",
            "English Name": "SICHUan KELUN-BIOTECH BIOPHARMACEUTICAL CO., LTD.",
            "Chinese Name": "科伦博泰",
            "Exchange": "Main Board",
            "Industry": "Healthcare",
            "Sub-Sector": "Antibody-Drug Conjugates",
            "Listing Date": "2026-04-24",
            "Offering Price": "HKD 135.00"
        },
        {
            "Ticker": "01455.HK",
            "CleanTicker": "01455",
            "English Name": "WILL SEMICONDUCTOR CO., LTD. SHANGHAI",
            "Chinese Name": "韦尔股份",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "CMOS Image Sensors",
            "Listing Date": "2026-04-23",
            "Offering Price": "HKD 98.40"
        },
        {
            "Ticker": "03911.HK",
            "CleanTicker": "03911",
            "English Name": "UNIGLOBOUR TIRE & RUBBER CO., LTD.",
            "Chinese Name": "赛轮轮胎",
            "Exchange": "Main Board",
            "Industry": "Consumer Discretionary",
            "Sub-Sector": "Tires & Rubber",
            "Listing Date": "2026-04-22",
            "Offering Price": "HKD 11.80"
        },
        {
            "Ticker": "08122.HK",
            "CleanTicker": "08122",
            "English Name": "SHENZHEN KAIFA TECHNOLOGY CO., LTD.",
            "Chinese Name": "深科技",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Electronics Manufacturing",
            "Listing Date": "2026-04-17",
            "Offering Price": "HKD 14.50"
        },
        {
            "Ticker": "02088.HK",
            "CleanTicker": "02088",
            "English Name": "ZHEJIANG JIAHUA ENERGY CHEMICAL INDUSTRY CO., LTD.",
            "Chinese Name": "嘉化能源",
            "Exchange": "Main Board",
            "Industry": "Materials",
            "Sub-Sector": "Chemical Processing",
            "Listing Date": "2026-04-16",
            "Offering Price": "HKD 9.60"
        },
        {
            "Ticker": "06188.HK",
            "CleanTicker": "06188",
            "English Name": "GUIZHOU PANJIANG REFINED COAL CO., LTD.",
            "Chinese Name": "盘江股份",
            "Exchange": "Main Board",
            "Industry": "Energy",
            "Sub-Sector": "Coal & Consumable Fuels",
            "Listing Date": "2026-04-15",
            "Offering Price": "HKD 6.40"
        },
        {
            "Ticker": "01233.HK",
            "CleanTicker": "01233",
            "English Name": "HUNAN ER-CANG BIOTECH CO., LTD.",
            "Chinese Name": "尔康制药",
            "Exchange": "Main Board",
            "Industry": "Healthcare",
            "Sub-Sector": "Excipients & Pharma",
            "Listing Date": "2026-04-10",
            "Offering Price": "HKD 4.30"
        },
        {
            "Ticker": "07311.HK",
            "CleanTicker": "07311",
            "English Name": "FUJIAN AONUO PHARMACEUTICAL CO., LTD.",
            "Chinese Name": "奥诺制药",
            "Exchange": "Main Board",
            "Industry": "Healthcare",
            "Sub-Sector": "Traditional Chinese Medicine",
            "Listing Date": "2026-04-09",
            "Offering Price": "HKD 12.10"
        },
        {
            "Ticker": "02811.HK",
            "CleanTicker": "02811",
            "English Name": "ANHUI GUOFENG NEW MATERIALS CO., LTD.",
            "Chinese Name": "国风新材",
            "Exchange": "Main Board",
            "Industry": "Materials",
            "Sub-Sector": "Plastic Films",
            "Listing Date": "2026-04-03",
            "Offering Price": "HKD 5.80"
        },
        {
            "Ticker": "06422.HK",
            "CleanTicker": "06422",
            "English Name": "BEIJING KINGPIG ENTERPRISE MANAGEMENT CO., LTD.",
            "Chinese Name": "京基企业管理",
            "Exchange": "Main Board",
            "Industry": "Financials",
            "Sub-Sector": "Investment Holdings",
            "Listing Date": "2026-04-02",
            "Offering Price": "HKD 7.50"
        },
        {
            "Ticker": "09899.HK",
            "CleanTicker": "09899",
            "English Name": "MONTAGE TECHNOLOGY CO., LTD.",
            "Chinese Name": "澜起科技",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Interface Chips",
            "Listing Date": "2026-03-31",
            "Offering Price": "HKD 67.50"
        },
        {
            "Ticker": "02522.HK",
            "CleanTicker": "02522",
            "English Name": "EASTROC BEVERAGE (GROUP) CO., LTD.",
            "Chinese Name": "东鹏饮料",
            "Exchange": "Main Board",
            "Industry": "Consumer Staples",
            "Sub-Sector": "Energy Drinks",
            "Listing Date": "2026-03-27",
            "Offering Price": "HKD 185.00"
        },
        {
            "Ticker": "06166.HK",
            "CleanTicker": "06166",
            "English Name": "MUYUAN FOODS CO., LTD.",
            "Chinese Name": "牧原股份",
            "Exchange": "Main Board",
            "Industry": "Consumer Staples",
            "Sub-Sector": "Agricultural Products",
            "Listing Date": "2026-03-26",
            "Offering Price": "HKD 42.10"
        },
        {
            "Ticker": "01788.HK",
            "CleanTicker": "01788",
            "English Name": "ZHEJIANG HUAYOU COBALT CO., LTD.",
            "Chinese Name": "华友钴业",
            "Exchange": "Main Board",
            "Industry": "Materials",
            "Sub-Sector": "Battery Raw Materials",
            "Listing Date": "2026-03-25",
            "Offering Price": "HKD 45.60"
        },
        {
            "Ticker": "03211.HK",
            "CleanTicker": "03211",
            "English Name": "SHENZHEN SC NEW ENERGY TECHNOLOGY CORP.",
            "Chinese Name": "盛弘股份",
            "Exchange": "Main Board",
            "Industry": "Industrials",
            "Sub-Sector": "Power Conversion Equipment",
            "Listing Date": "2026-03-20",
            "Offering Price": "HKD 29.80"
        },
        {
            "Ticker": "08233.HK",
            "CleanTicker": "08233",
            "English Name": "QINGDAO SENTURY TIRE CO., LTD.",
            "Chinese Name": "森麒麟",
            "Exchange": "Main Board",
            "Industry": "Consumer Discretionary",
            "Sub-Sector": "Automotive Tires",
            "Listing Date": "2026-03-19",
            "Offering Price": "HKD 19.30"
        },
        {
            "Ticker": "02177.HK",
            "CleanTicker": "02177",
            "English Name": "SUZHOU TFC OPTICAL COMMUNICATION CO., LTD.",
            "Chinese Name": "天孚通信",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Optical Components",
            "Listing Date": "2026-03-18",
            "Offering Price": "HKD 110.20"
        },
        {
            "Ticker": "06333.HK",
            "CleanTicker": "06333",
            "English Name": "HUBEI MINGDE BIOTECHNOLOGY CO., LTD.",
            "Chinese Name": "明德生物",
            "Exchange": "Main Board",
            "Industry": "Healthcare",
            "Sub-Sector": "In Vitro Diagnostics",
            "Listing Date": "2026-03-13",
            "Offering Price": "HKD 25.40"
        },
        {
            "Ticker": "01511.HK",
            "CleanTicker": "01511",
            "English Name": "SHANGHAI JUNSHI BIOSCIENCES CO., LTD.",
            "Chinese Name": "君实生物",
            "Exchange": "Main Board",
            "Industry": "Healthcare",
            "Sub-Sector": "Monoclonal Antibodies",
            "Listing Date": "2026-03-12",
            "Offering Price": "HKD 31.50"
        },
        {
            "Ticker": "03622.HK",
            "CleanTicker": "03622",
            "English Name": "NANJING HIGH ACCURACY GEAR GROUP CO., LTD.",
            "Chinese Name": "高速齿轮",
            "Exchange": "Main Board",
            "Industry": "Industrials",
            "Sub-Sector": "Transmission Equipment",
            "Listing Date": "2026-03-11",
            "Offering Price": "HKD 13.70"
        },
        {
            "Ticker": "02911.HK",
            "CleanTicker": "02911",
            "English Name": "GANFENGLITHIUM GROUP CO., LTD.",
            "Chinese Name": "赣锋锂业",
            "Exchange": "Main Board",
            "Industry": "Materials",
            "Sub-Sector": "Lithium Compounds",
            "Listing Date": "2026-03-06",
            "Offering Price": "HKD 38.40"
        },
        {
            "Ticker": "07122.HK",
            "CleanTicker": "07122",
            "English Name": "SHANDONG HEAD WATER SOLUBLE POLYMER CO., LTD.",
            "Chinese Name": "赫达股份",
            "Exchange": "Main Board",
            "Industry": "Materials",
            "Sub-Sector": "Fine Chemicals",
            "Listing Date": "2026-03-05",
            "Offering Price": "HKD 21.90"
        },
        {
            "Ticker": "01933.HK",
            "CleanTicker": "01933",
            "English Name": "BEIJING BDSTAR NAVIGATION CO., LTD.",
            "Chinese Name": "北斗星通",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Satellite Navigation",
            "Listing Date": "2026-03-04",
            "Offering Price": "HKD 26.80"
        },
        {
            "Ticker": "06511.HK",
            "CleanTicker": "06511",
            "English Name": "ZHEJIANG SUPOR COOKWARE CO., LTD.",
            "Chinese Name": "苏泊尔",
            "Exchange": "Main Board",
            "Industry": "Consumer Discretionary",
            "Sub-Sector": "Home Appliances",
            "Listing Date": "2026-02-27",
            "Offering Price": "HKD 52.00"
        },
        {
            "Ticker": "02411.HK",
            "CleanTicker": "02411",
            "English Name": "GUANGDONG HAID GROUP CO., LTD.",
            "Chinese Name": "海大集团",
            "Exchange": "Main Board",
            "Industry": "Consumer Staples",
            "Sub-Sector": "Animal Feed & Farming",
            "Listing Date": "2026-02-26",
            "Offering Price": "HKD 49.30"
        },
        {
            "Ticker": "08166.HK",
            "CleanTicker": "08166",
            "English Name": "SICHUAN YAHUA INDUSTRIAL GROUP CO., LTD.",
            "Chinese Name": "雅化集团",
            "Exchange": "Main Board",
            "Industry": "Materials",
            "Sub-Sector": "Lithium Salts & Explosives",
            "Listing Date": "2026-02-25",
            "Offering Price": "HKD 16.40"
        },
        {
            "Ticker": "01288.HK",
            "CleanTicker": "01288",
            "English Name": "SHENZHEN KINWONG ELECTRONIC CO., LTD.",
            "Chinese Name": "景旺电子",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Printed Circuit Boards",
            "Listing Date": "2026-02-13",
            "Offering Price": "HKD 23.50"
        },
        {
            "Ticker": "03511.HK",
            "CleanTicker": "03511",
            "English Name": "CHONGQING SANFENG ENVIRONMENT GROUP CORP., LTD.",
            "Chinese Name": "三峰环境",
            "Exchange": "Main Board",
            "Industry": "Utilities",
            "Sub-Sector": "Waste Management",
            "Listing Date": "2026-02-12",
            "Offering Price": "HKD 7.10"
        },
        {
            "Ticker": "07233.HK",
            "CleanTicker": "07233",
            "English Name": "JIANGSU YOKE TECHNOLOGY CO., LTD.",
            "Chinese Name": "雅克科技",
            "Exchange": "Main Board",
            "Industry": "Materials",
            "Sub-Sector": "Semiconductor Materials",
            "Listing Date": "2026-02-06",
            "Offering Price": "HKD 41.20"
        },
        {
            "Ticker": "02288.HK",
            "CleanTicker": "02288",
            "English Name": "HUNAN SUGAR INDUSTRY CO., LTD.",
            "Chinese Name": "湖南糖业",
            "Exchange": "Main Board",
            "Industry": "Consumer Staples",
            "Sub-Sector": "Food Production",
            "Listing Date": "2026-02-05",
            "Offering Price": "HKD 5.40"
        },
        {
            "Ticker": "08801.HK",
            "CleanTicker": "08801",
            "English Name": "KNOWLEDGE ATLAS TECHNOLOGY LIMITED",
            "Chinese Name": "知图科技",
            "Exchange": "GEM",
            "Industry": "Information Technology",
            "Sub-Sector": "Knowledge Graph AI",
            "Listing Date": "2026-01-08",
            "Offering Price": "HKD 18.00"
        },
        {
            "Ticker": "09888.HK",
            "CleanTicker": "09888",
            "English Name": "MERDEKA BATTERY MATERIALS TBK PT",
            "Chinese Name": "迈德卡电池材料",
            "Exchange": "Main Board",
            "Industry": "Materials",
            "Sub-Sector": "Mining & Metals",
            "Listing Date": "2026-01-05",
            "Offering Price": "HKD 28.50"
        },
        {
            "Ticker": "02500.HK",
            "CleanTicker": "02500",
            "English Name": "SHANGHAI AI-ROBOTICS TECH CO., LTD.",
            "Chinese Name": "上海智能机器人",
            "Exchange": "Main Board",
            "Industry": "Industrials",
            "Sub-Sector": "Humanoid Robotics",
            "Listing Date": "2026-01-02",
            "Offering Price": "HKD 65.00"
        },
        {
            "Ticker": "02501.HK",
            "CleanTicker": "02501",
            "English Name": "QUANTUM COMPUTING GLOBAL INC.",
            "Chinese Name": "量子计算全球",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Quantum Technology",
            "Listing Date": "2026-01-02",
            "Offering Price": "HKD 110.00"
        },
        {
            "Ticker": "02502.HK",
            "CleanTicker": "02502",
            "English Name": "NEURALINK ASIA PACIFIC LIMITED",
            "Chinese Name": "脑机接口亚太",
            "Exchange": "Main Board",
            "Industry": "Healthcare",
            "Sub-Sector": "Neural Engineering",
            "Listing Date": "2026-01-02",
            "Offering Price": "HKD 150.00"
        },
        {
            "Ticker": "02503.HK",
            "CleanTicker": "02503",
            "English Name": "FUSION ENERGY TECHNOLOGIES CORP.",
            "Chinese Name": "聚变能源科技",
            "Exchange": "Main Board",
            "Industry": "Utilities",
            "Sub-Sector": "Clean Energy",
            "Listing Date": "2026-01-02",
            "Offering Price": "HKD 88.00"
        },
        {
            "Ticker": "02504.HK",
            "CleanTicker": "02504",
            "English Name": "SYNTHETIC BIOLOGY GLOBAL LTD.",
            "Chinese Name": "合成生物全球",
            "Exchange": "Main Board",
            "Industry": "Healthcare",
            "Sub-Sector": "Synthetic Biology",
            "Listing Date": "2026-01-02",
            "Offering Price": "HKD 45.00"
        }
    ]
