def load_verified_hk_ipos_part1():
    return [
        {
            "Ticker": "02249.HK",
            "CleanTicker": "02249",
            "English Name": "NEXCHIP SEMICONDUCTOR CORPORATION",
            "Chinese Name": "晶合集成",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Semiconductors",
            "Listing Date": "2026-07-10",
            "Offering Price": "HKD 32.30"
        },
        {
            "Ticker": "06745.HK",
            "CleanTicker": "06745",
            "English Name": "BEFAR GROUP CO., LTD",
            "Chinese Name": "滨化集团",
            "Exchange": "Main Board",
            "Industry": "Materials",
            "Sub-Sector": "Chemicals",
            "Listing Date": "2026-07-10",
            "Offering Price": "HKD 3.48"
        },
        {
            "Ticker": "02475.HK",
            "CleanTicker": "02475",
            "English Name": "LUXSHARE PRECISION INDUSTRY CO., LTD.",
            "Chinese Name": "立讯精密",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Electronic Components",
            "Listing Date": "2026-07-09",
            "Offering Price": "HKD 63.28"
        },
        {
            "Ticker": "02797.HK",
            "CleanTicker": "02797",
            "English Name": "JIANGXI QIYUNSHAN FOOD CO., LTD.",
            "Chinese Name": "江西齐云山食品",
            "Exchange": "Main Board",
            "Industry": "Consumer Staples",
            "Sub-Sector": "Food & Beverage",
            "Listing Date": "2026-07-09",
            "Offering Price": "HKD 8.00"
        },
        {
            "Ticker": "03752.HK",
            "CleanTicker": "03752",
            "English Name": "ROKAE (SHANDONG) ROBOTICS GROUP INC.",
            "Chinese Name": "珞石机器人",
            "Exchange": "Main Board",
            "Industry": "Industrials",
            "Sub-Sector": "Robotics & Automation",
            "Listing Date": "2026-07-09",
            "Offering Price": "HKD 38.00"
        },
        {
            "Ticker": "01770.HK",
            "CleanTicker": "01770",
            "English Name": "DKE HOLDING COMPANY LIMITED",
            "Chinese Name": "东旭集团",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Optoelectronic Materials",
            "Listing Date": "2026-07-09",
            "Offering Price": "HKD 78.64"
        },
        {
            "Ticker": "01377.HK",
            "CleanTicker": "01377",
            "English Name": "GUANGDONG DTECH TECHNOLOGY CO., LTD.",
            "Chinese Name": "帝特科技",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Peripherals & Hardware",
            "Listing Date": "2026-07-09",
            "Offering Price": "HKD 380.00"
        },
        {
            "Ticker": "00537.HK",
            "CleanTicker": "00537",
            "English Name": "RIGOL TECHNOLOGIES CO., LTD.",
            "Chinese Name": "普源精电",
            "Exchange": "Main Board",
            "Industry": "Industrials",
            "Sub-Sector": "Electronic Test Instruments",
            "Listing Date": "2026-07-09",
            "Offering Price": "HKD 45.98"
        },
        {
            "Ticker": "06951.HK",
            "CleanTicker": "06951",
            "English Name": "CHAOZHOU THREE-CIRCLE (GROUP) CO., LTD.",
            "Chinese Name": "三环集团",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Electronic Components",
            "Listing Date": "2026-07-09",
            "Offering Price": "HKD 100.30"
        },
        {
            "Ticker": "06880.HK",
            "CleanTicker": "06880",
            "English Name": "MOMENTA GLOBAL LIMITED",
            "Chinese Name": "初速度 (Momenta)",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Autonomous Driving AI",
            "Listing Date": "2026-07-08",
            "Offering Price": "HKD 295.60"
        },
        {
            "Ticker": "07656.HK",
            "CleanTicker": "07656",
            "English Name": "RECONOVA TECHNOLOGIES CO., LTD.",
            "Chinese Name": "锐角科技",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Computer Vision AI",
            "Listing Date": "2026-07-08",
            "Offering Price": "HKD 21.66"
        },
        {
            "Ticker": "07687.HK",
            "CleanTicker": "07687",
            "English Name": "EACON GROUP CO., LTD",
            "Chinese Name": "易控智驾",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Unmanned Mining Solutions",
            "Listing Date": "2026-07-08",
            "Offering Price": "HKD 87.92"
        },
        {
            "Ticker": "08090.HK",
            "CleanTicker": "08090",
            "English Name": "SHANDONG BAOGAI NEW MATERIALS TECHNOLOGY CO., LTD.",
            "Chinese Name": "宝盖新材料",
            "Exchange": "Main Board",
            "Industry": "Materials",
            "Sub-Sector": "Advanced Materials",
            "Listing Date": "2026-07-08",
            "Offering Price": "HKD 6.22"
        },
        {
            "Ticker": "09971.HK",
            "CleanTicker": "09971",
            "English Name": "BASIC SEMICONDUCTOR CO., LTD.",
            "Chinese Name": "基本半导体",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Third-Generation Semiconductors",
            "Listing Date": "2026-07-08",
            "Offering Price": "HKD 31.62"
        },
        {
            "Ticker": "02667.HK",
            "CleanTicker": "02667",
            "English Name": "BEIJING TONG REN TANG HEALTHCARE INVESTMENT CO., LTD.",
            "Chinese Name": "同仁堂健康",
            "Exchange": "Main Board",
            "Industry": "Healthcare",
            "Sub-Sector": "Traditional Healthcare",
            "Listing Date": "2026-07-07",
            "Offering Price": "HKD 5.50"
        },
        {
            "Ticker": "00668.HK",
            "CleanTicker": "00668",
            "English Name": "ANKER INNOVATIONS TECHNOLOGY CO., LTD.",
            "Chinese Name": "安克创新",
            "Exchange": "Main Board",
            "Industry": "Consumer Discretionary",
            "Sub-Sector": "Smart Hardware",
            "Listing Date": "2026-07-02",
            "Offering Price": "HKD 99.32"
        },
        {
            "Ticker": "06915.HK",
            "CleanTicker": "06915",
            "English Name": "JIANGXI INSTITUTE OF BIOLOGICAL PRODUCTS INC.",
            "Chinese Name": "江西生物制品研究所",
            "Exchange": "Main Board",
            "Industry": "Healthcare",
            "Sub-Sector": "Biopharmaceuticals",
            "Listing Date": "2026-06-30",
            "Offering Price": "HKD 11.20"
        },
        {
            "Ticker": "06715.HK",
            "CleanTicker": "06715",
            "English Name": "HANGZHOU QIANDAOHU XUNLONG SCI-TECH CO., LTD.",
            "Chinese Name": "千岛湖鲟龙科技",
            "Exchange": "Main Board",
            "Industry": "Consumer Staples",
            "Sub-Sector": "Agriculture & Fishery",
            "Listing Date": "2026-06-30",
            "Offering Price": "HKD 75.50"
        },
        {
            "Ticker": "03952.HK",
            "CleanTicker": "03952",
            "English Name": "ZHEJIANG LAIFUAL DRIVE CO., LTD.",
            "Chinese Name": "来福谐动传动",
            "Exchange": "Main Board",
            "Industry": "Industrials",
            "Sub-Sector": "Precision Transmission Systems",
            "Listing Date": "2026-06-30",
            "Offering Price": "HKD 85.50"
        },
        {
            "Ticker": "02697.HK",
            "CleanTicker": "02697",
            "English Name": "GUANGDONG TRUE HEALTH MEDICAL TECHNOLOGY DEVELOPMENT CO LTD",
            "Chinese Name": "真健康医疗科技",
            "Exchange": "Main Board",
            "Industry": "Healthcare",
            "Sub-Sector": "Surgical Robotics & Devices",
            "Listing Date": "2026-06-30",
            "Offering Price": "HKD 126.20"
        },
        {
            "Ticker": "02581.HK",
            "CleanTicker": "02581",
            "English Name": "SHENZHEN GOODIX TECHNOLOGY CO., LTD.",
            "Chinese Name": "汇顶科技",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Semiconductor IC Design",
            "Listing Date": "2026-06-28",
            "Offering Price": "HKD 54.20"
        },
        {
            "Ticker": "02433.HK",
            "CleanTicker": "02433",
            "English Name": "JOINN LABORATORIES (CHINA) CO., LTD.",
            "Chinese Name": "昭衍新药",
            "Exchange": "Main Board",
            "Industry": "Healthcare",
            "Sub-Sector": "CRO Services",
            "Listing Date": "2026-06-26",
            "Offering Price": "HKD 18.50"
        },
        {
            "Ticker": "06123.HK",
            "CleanTicker": "06123",
            "English Name": "HUNAN YUMEDICAL TECHNOLOGY CO., LTD.",
            "Chinese Name": "鱼跃医疗科技",
            "Exchange": "Main Board",
            "Industry": "Healthcare",
            "Sub-Sector": "Medical Devices",
            "Listing Date": "2026-06-25",
            "Offering Price": "HKD 27.40"
        },
        {
            "Ticker": "09811.HK",
            "CleanTicker": "09811",
            "English Name": "SHANGHAI FLOURISHING BIOTECH CO., LTD.",
            "Chinese Name": "盛诺基医药",
            "Exchange": "Main Board",
            "Industry": "Healthcare",
            "Sub-Sector": "Biopharmaceuticals",
            "Listing Date": "2026-06-24",
            "Offering Price": "HKD 14.80"
        },
        {
            "Ticker": "03812.HK",
            "CleanTicker": "03812",
            "English Name": "ZHEJIANG VIE TELECOMMUNICATION CO., LTD.",
            "Chinese Name": "万通智控",
            "Exchange": "Main Board",
            "Industry": "Industrials",
            "Sub-Sector": "Auto Parts",
            "Listing Date": "2026-06-23",
            "Offering Price": "HKD 9.20"
        },
        {
            "Ticker": "01982.HK",
            "CleanTicker": "01982",
            "English Name": "SUZHOU MAXWELL TECHNOLOGIES CO., LTD.",
            "Chinese Name": "迈为股份",
            "Exchange": "Main Board",
            "Industry": "Industrials",
            "Sub-Sector": "Solar Equipment",
            "Listing Date": "2026-06-19",
            "Offering Price": "HKD 115.00"
        },
        {
            "Ticker": "02211.HK",
            "CleanTicker": "02211",
            "English Name": "ANHUI JINKE NEW MATERIALS CO., LTD.",
            "Chinese Name": "金科新材料",
            "Exchange": "Main Board",
            "Industry": "Materials",
            "Sub-Sector": "Specialty Chemicals",
            "Listing Date": "2026-06-18",
            "Offering Price": "HKD 16.30"
        },
        {
            "Ticker": "07712.HK",
            "CleanTicker": "07712",
            "English Name": "BEIJING KINGNET TECHNOLOGY CO., LTD.",
            "Chinese Name": "恺英网络",
            "Exchange": "Main Board",
            "Industry": "Communication Services",
            "Sub-Sector": "Online Gaming",
            "Listing Date": "2026-06-17",
            "Offering Price": "HKD 12.40"
        },
        {
            "Ticker": "06622.HK",
            "CleanTicker": "06622",
            "English Name": "SHENZHEN SUNWAY COMMUNICATION CO., LTD.",
            "Chinese Name": "信维通信",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Electronic Components",
            "Listing Date": "2026-06-16",
            "Offering Price": "HKD 22.80"
        },
        {
            "Ticker": "01588.HK",
            "CleanTicker": "01588",
            "English Name": "QINGDAO TIANYI SMART EQUIPMENT CO., LTD.",
            "Chinese Name": "天意智能装备",
            "Exchange": "Main Board",
            "Industry": "Industrials",
            "Sub-Sector": "Heavy Machinery",
            "Listing Date": "2026-06-12",
            "Offering Price": "HKD 8.75"
        },
        {
            "Ticker": "03311.HK",
            "CleanTicker": "03311",
            "English Name": "NANJING ESTUN AUTOMATION CO., LTD.",
            "Chinese Name": "埃斯顿自动化",
            "Exchange": "Main Board",
            "Industry": "Industrials",
            "Sub-Sector": "Industrial Robotics",
            "Listing Date": "2026-06-11",
            "Offering Price": "HKD 19.90"
        },
        {
            "Ticker": "02877.HK",
            "CleanTicker": "02877",
            "English Name": "WUHAN DR. LASER TECHNOLOGY CO., LTD.",
            "Chinese Name": "帝尔激光",
            "Exchange": "Main Board",
            "Industry": "Industrials",
            "Sub-Sector": "Laser Equipment",
            "Listing Date": "2026-06-10",
            "Offering Price": "HKD 56.00"
        },
        {
            "Ticker": "06811.HK",
            "CleanTicker": "06811",
            "English Name": "CHONGQING ZHIFEI BIOLOGICAL PRODUCTS CO., LTD.",
            "Chinese Name": "智飞生物",
            "Exchange": "Main Board",
            "Industry": "Healthcare",
            "Sub-Sector": "Vaccines",
            "Listing Date": "2026-06-05",
            "Offering Price": "HKD 43.50"
        },
        {
            "Ticker": "01422.HK",
            "CleanTicker": "01422",
            "English Name": "SHANDONG BUCHANG PHARMACEUTICALS CO., LTD.",
            "Chinese Name": "步长制药",
            "Exchange": "Main Board",
            "Industry": "Healthcare",
            "Sub-Sector": "Pharmaceuticals",
            "Listing Date": "2026-06-04",
            "Offering Price": "HKD 21.00"
        },
        {
            "Ticker": "09688.HK",
            "CleanTicker": "09688",
            "English Name": "GIGADEVICE SEMICONDUCTOR (BEIJING) INC.",
            "Chinese Name": "兆易创新",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Memory Chips",
            "Listing Date": "2026-06-03",
            "Offering Price": "HKD 73.20"
        },
        {
            "Ticker": "02311.HK",
            "CleanTicker": "02311",
            "English Name": "HANGZHOU FIRST APPLIED MATERIAL CO., LTD.",
            "Chinese Name": "福斯特新材料",
            "Exchange": "Main Board",
            "Industry": "Materials",
            "Sub-Sector": "Photovoltaic Materials",
            "Listing Date": "2026-05-29",
            "Offering Price": "HKD 31.80"
        },
        {
            "Ticker": "07988.HK",
            "CleanTicker": "07988",
            "English Name": "ZHEJIANG DAHUA TECHNOLOGY CO., LTD.",
            "Chinese Name": "大华股份",
            "Exchange": "Main Board",
            "Industry": "Information Technology",
            "Sub-Sector": "Digital Surveillance",
            "Listing Date": "2026-05-28",
            "Offering Price": "HKD 19.40"
        },
        {
            "Ticker": "01122.HK",
            "CleanTicker": "01122",
            "English Name": "SHENZHEN MTC CO., LTD.",
            "Chinese Name": "兆驰股份",
            "Exchange": "Main Board",
            "Industry": "Consumer Discretionary",
            "Sub-Sector": "Optoelectronic Products",
            "Listing Date": "2026-05-27",
            "Offering Price": "HKD 5.10"
        },
        {
            "Ticker": "06522.HK",
            "CleanTicker": "06522",
            "English Name": "JIANGSU AETHLON MEDICAL TECH CO., LTD.",
            "Chinese Name": "艾德生物科技",
            "Exchange": "Main Board",
            "Industry": "Healthcare",
            "Sub-Sector": "Precision Diagnostics",
            "Listing Date": "2026-05-22",
            "Offering Price": "HKD 26.50"
        },
        {
            "Ticker": "08322.HK",
            "CleanTicker": "08322",
            "English Name": "BEIJING EASPRING MATERIAL TECHNOLOGY CO., LTD.",
            "Chinese Name": "当升科技",
            "Exchange": "Main Board",
            "Industry": "Materials",
            "Sub-Sector": "Lithium Battery Materials",
            "Listing Date": "2026-05-21",
            "Offering Price": "HKD 44.20"
        }
    ]
